import { createRestApp } from "#/app";
import { runProactiveSweep } from "#/scheduled";

// Worker entry for vitest-pool-workers + non-Flue wrangler contexts. The real
// production entry is generated by `flue build` from .flue/ (it serves these
// same REST routes plus the Flue agent/workflow/run routes). This thin entry
// serves the REST surface + the weekly cron; agent traffic is Flue-only.
const app = createRestApp();

export default {
  fetch(request, env, ctx): Promise<Response> | Response {
    return app.fetch(request, env, ctx);
  },
  async scheduled(_controller, env): Promise<void> {
    await runProactiveSweep(env);
  },
} satisfies ExportedHandler<Env>;

// Workflow class the runtime binds by name (wrangler.jsonc).
export { WorkerJobWorkflow } from "#/workflows/worker-job";
