import { createRestApp } from "#/app";
import cloudflare from "#/cloudflare";

// Worker entry for vitest-pool-workers and non-Flue wrangler contexts. The
// production entry is generated by `flue build` (src/app.ts, src/cloudflare.ts,
// src/agents/*). This one reuses cloudflare.ts's non-HTTP handlers and Workflow
// binding so the two entries can't drift; it just omits `flue()`, which needs
// the generated runtime.
const app = createRestApp();

export default {
  fetch(request, env, ctx): Promise<Response> | Response {
    return app.fetch(request, env, ctx);
  },
  scheduled: cloudflare.scheduled,
} satisfies ExportedHandler<Env>;

// Workflow class the runtime binds by name (wrangler.jsonc).
export { WorkerJobWorkflow } from "#/cloudflare";
