import cloudflare from "#/cloudflare";
import { createRestApp } from "#/rest-app";

// Worker entry for vitest-pool-workers + non-Flue wrangler contexts. The real
// production entry is generated by `flue build` (src/app.ts + src/cloudflare.ts
// + src/agents/*). This entry pairs the REST surface with the SAME non-HTTP
// handlers + Workflow binding that cloudflare.ts hands the Flue build, so the
// two entries can't drift. The only difference from production: no `flue()`
// agent routes (they need the generated runtime; agent traffic is Flue-only).
const app = createRestApp();

export default {
  fetch(request, env, ctx): Promise<Response> | Response {
    return app.fetch(request, env, ctx);
  },
  scheduled: cloudflare.scheduled,
} satisfies ExportedHandler<Env>;

// Workflow class the runtime binds by name (wrangler.jsonc).
export { WorkerJobWorkflow } from "#/cloudflare";
