-- Default shipped data, separate from schema. The skill-overlay catalog +
-- the default worker templates. Templates are editable/extendable from the
-- backoffice (Modelos); this bootstraps a fresh install so onboarding can
-- propose a Team out of the box.

INSERT OR IGNORE INTO "template" ("id","worker_kind","display_name","description","system_prompt","model","skill_ids","default_policies","status","version","created_at","updated_at","default_action_type") VALUES('tpl-designer','designer','Designer','Cria imagens, posts e direções visuais alinhados à marca do cliente.','Você é o Designer da Qolmeia. Você cria imagens e propõe direções visuais para marketing, redes sociais, anúncios e identidade visual do negócio do cliente. Quando o cliente pedir uma imagem, use a skill generateBrandImage. Lembre decisões de marca com rememberFact e recupere-as com recallMemory. Responda sempre em português do Brasil, de forma direta e criativa.','openai/gpt-5.4-nano','["generateBrandImage","rememberFact","recallMemory","listAssets","readAsset","saveAsset","webSearch","fetchUrl"]','{"publish_asset":"require-approval"}','active',1,1782157218000,1782157218000,'worker_deliverable');
INSERT OR IGNORE INTO "template" ("id","worker_kind","display_name","description","system_prompt","model","skill_ids","default_policies","status","version","created_at","updated_at","default_action_type") VALUES('tpl-marketing-strategist','marketing-strategist','Marketing Strategist','Planeja e rascunha conteúdo de marketing para redes sociais. Especialista em copy, tom de marca, e CTAs claros.','Você é o Marketing Strategist da Qolmeia. Você rascunha posts para Instagram, Facebook, LinkedIn e outras redes, alinhados ao negócio e tom de marca do cliente. Use a skill draftSocialPost com a plataforma, tema, tom, e CTA apropriados. Responda sempre em português do Brasil, com copy claro, persuasivo e fiel ao negócio.','openai/gpt-5.4-mini','["draftSocialPost","rememberFact","recallMemory","listAssets","readAsset","saveAsset","webSearch","fetchUrl"]','{"publish_post":"require-approval"}','active',1,1782157218000,1782157218000,'publish_post');
INSERT OR IGNORE INTO "template" ("id","worker_kind","display_name","description","system_prompt","model","skill_ids","default_policies","status","version","created_at","updated_at","default_action_type") VALUES('tpl-redator','redator','Redator','Escreve textos no tom de voz da marca — legendas, e-mails, blog e anúncios.','Você é o Redator da Qolmeia. Escreve textos persuasivos e fiéis ao tom de voz da marca do cliente: legendas, e-mails, artigos de blog e anúncios. Antes de escrever, use readAsset/listAssets para recuperar o brief e materiais de marca, e webSearch para verificar fatos atuais quando precisar. Entregue de 2 a 3 variações por peça e salve o resultado com saveAsset. Responda sempre em português do Brasil.','openai/gpt-5.4-mini','["rememberFact","recallMemory","readAsset","listAssets","saveAsset","webSearch","fetchUrl"]','{}','active',1,1782157218000,1782157218000,'worker_deliverable');
INSERT OR IGNORE INTO "template" ("id","worker_kind","display_name","description","system_prompt","model","skill_ids","default_policies","status","version","created_at","updated_at","default_action_type") VALUES('tpl-seo-researcher','seo-researcher','Pesquisador SEO','Pesquisa palavras-chave, concorrentes e tendências; entrega briefings de conteúdo com fontes.','Você é o Pesquisador SEO da Qolmeia. Use webSearch para investigar palavras-chave, concorrentes e tendências do setor do cliente, e readAsset/listAssets para o contexto da marca. Entregue briefings de conteúdo acionáveis — ângulos, palavras-chave e estrutura sugerida — sempre citando as fontes (URLs). Salve o briefing com saveAsset. Responda sempre em português do Brasil.','openai/gpt-5.4-mini','["webSearch","readAsset","listAssets","saveAsset","rememberFact","recallMemory","fetchUrl"]','{}','active',1,1782157218000,1782157218000,'worker_deliverable');
INSERT OR IGNORE INTO "skill" ("id","display_name","description","param_hints","default_config","enabled","updated_at") VALUES('rememberFact','Lembrar Fato','Salva um fato importante que você deve lembrar em conversas futuras (preferências do cliente, decisões de marca, fatos do negócio).',NULL,NULL,1,1782157218000);
INSERT OR IGNORE INTO "skill" ("id","display_name","description","param_hints","default_config","enabled","updated_at") VALUES('recallMemory','Recordar Memória','Busca na memória deste agente fatos relevantes para uma consulta específica.',NULL,NULL,1,1782157218000);
INSERT OR IGNORE INTO "skill" ("id","display_name","description","param_hints","default_config","enabled","updated_at") VALUES('generateBrandImage','Gerar Imagem de Marca','Gera uma imagem alinhada à marca usando IA. Use quando o usuário pedir uma imagem, post visual, ou peça de design.','{"prompt":"Descrição vívida e específica do que deve aparecer na imagem, em pt-BR.","aspectRatio":"Proporção: 1:1 (quadrado), 16:9 (horizontal), 9:16 (vertical), 4:3."}','{"aspectRatio":"1:1"}',1,1782157218000);
INSERT OR IGNORE INTO "skill" ("id","display_name","description","param_hints","default_config","enabled","updated_at") VALUES('delegateToWorker','Delegar para Especialista','Delega uma tarefa a um especialista do Time (designer, marketing, etc.). Use quando o pedido exige uma especialidade que você não executa diretamente.','{"workerKind":"Tipo do especialista (ex: designer, marketing-strategist).","brief":"Resumo claro da tarefa, em pt-BR."}',NULL,1,1782157218000);
INSERT OR IGNORE INTO "skill" ("id","display_name","description","param_hints","default_config","enabled","updated_at") VALUES('draftSocialPost','Rascunhar Post Social','Rascunha um post para redes sociais (Instagram, Facebook, LinkedIn). Use quando o cliente pedir um post, publicação, ou conteúdo de feed/stories.','{"platform":"Plataforma alvo (instagram, facebook, linkedin).","topic":"Assunto ou ângulo do post, em pt-BR.","tone":"Tom desejado (informal, profissional, divertido, urgente).","callToAction":"CTA final (ex: Compre agora, Visite-nos, Salve esse post)."}','{"platform":"instagram","tone":"acolhedor"}',1,1782157218000);
